### ISSUE TITLE
sparql ontology fails

### ISSUE THREAD

**Issue by zywind** [mmberg/nadia#3]
Hi,

Lexicon.owl uses this sparql namespace: http://www.topbraidcomposer.org/owl/2006/09/sparql.owl#. It seems that url is no longer reachable and it is causing the application to stall at the start.  Should it be updated to http://www.w3.org/ns/sparql-service-description# instead?  I'm not familiar with ontology at all, so I could be wrong.

**Comment by mmberg** [comment]
Do you have any warnings or log output on that? I've just tried to access the URL and it still exists. Also, even if it not existed it shouldn't matter because it is only a namespace. It has been automatically added by Topbraid and allows to store SPARQL queries as metadata within the ontology for future reference. This should not have any influence on the actual ontology.

**Comment by zywind** [comment]
OK. I think it comes back now. It was just very slow to start up when the topbraid url was down.
